# https://github.com/Homebrew/homebrew-bundle
# Install path for cask apps
cask_args appdir: '/Applications'

#### Tap into cask-fonts
tap 'homebrew/cask-fonts'

#### Install brew packages
brew 'git'
brew 'bash-completion'
brew 'brew-cask-completion'
brew 'dockutil'
brew 'fzf'
brew 'gcc'
brew 'gdbm'
brew 'glances'
brew 'glib'
brew 'gnupg'
brew 'gnupg2'
brew 'gnutls'
brew 'go'
brew 'imagemagick'
brew 'jq'
brew 'libgcrypt'
brew 'libunistring'
brew 'libusb'
brew 'libxml2'
brew 'netcat'
brew 'nmap'
brew 'node'
brew 'speedtest-cli'
brew 'sqlite'
brew 'telnet'
brew 'the_silver_searcher'
brew 'tree'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'

#### Install cask fonts
cask 'font-meslo-for-powerline'

#### Install cask apps
cask '1password'
cask 'atom'
cask 'balenaetcher'
cask 'docker'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'minikube'
cask 'platypus'
cask 'slack'
cask 'spectacle'
cask 'suspicious-package'
cask 'vagrant'
cask 'vagrant-manager'
cask 'vlc'
cask 'virtualbox'
cask 'wireshark'
cask 'xquartz'
